# Project information
site_name: DBA100.COM
site_description: 'MySQL、MySQL8、数据库运维自动化'
site_author: 'duliang'
site_url: 'http://www.dba100.com'

# Copyright
copyright: 'Copyright &copy; 2020 <a href="http://www.dba100.com">dba100.com</a> <a href="http://beian.miit.gov.cn" target="_balank">苏ICP备17064193号</a>'

# Configuration
theme:
  name: material
  language: 'zh'
  features:
    - tabs

# Extensions
markdown_extensions:
  - pymdownx.inlinehilite
  - markdown.extensions.codehilite:
      guess_lang: false

nav:
  - '首页': index.md
  - '关于': about.md
  - 'MySQL':
    - 'MySQL简介': mysql/index.md
    - '连接登陆': mysql/programs-client/mysql.md
    - '获得MySQL帮助': mysql/help.md
    - '安全设置': 
      - '安装之后安全设置': mysql/security/security.md
      - '一般安全问题': mysql/security/general-security-issues.md
    - '用户管理': mysql/user.md
    - 'MySQL程序': mysql/programs.md
    - 'MySQL服务器管理': 
      - '配置和状态信息': mysql/server-administration/server-configuration.md
    - '备份与恢复':
      - '备份恢复类型与方法': mysql/backup-and-recovery/backup-types-and-methods.md
      - 'mysqldump逻辑备份': mysql/backup-and-recovery/mysqldump.md
    - '函数与操作符': functions_and_operators.md
    - 'SQL 语句': mysql/sql.md
  - 'MySQL 8':
    - "MySQL 8 简介": mysql8/index.md
#  - 'Redis':
#    - 'Redis 简介': index.md
#  - 'Memcached':
#    - 'Memcached 简介': index.md
#  - 'MongoDB':
#    - 'MongoDB 简介': index.md
#  - 'Elasticsearch':
#    - 'Elasticsearch 简介': index.md

